### ISSUE TITLE
Can jump into the wall (and not get out)

### ISSUE THREAD

**Issue by DarrenCook** [superpowers-extra/discover-superpowers-game#1]
(Not an issue with the demo, as delivered, as you need to hack it a bit first.)

If I change the player's jump velocity from 30 to 60 (line 91 of script.ts for Player Behaviour), then jump when near a wall it becomes possible to go through the wall and disappear. (With no way to get out!)

I was surprised that the physics of the wall was not the same at all heights? Was this deliberate, and if so, why? (e.g. performance?)

**Comment by bilou84** [comment]
Thanks for the report again. Don't have a very good reason to give you. The wall was big enough for our jump ability, so well...
